# Generated by Django 6.0.3 on 2026-03-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=123456, max_length=128),
            preserve_default=False,
        ),
    ]
