# Generated by Django 6.0.3 on 2026-03-10 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('pay_at', models.DateTimeField(auto_now_add=True)),
                ('pay_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.paymethod')),
            ],
        ),
    ]
